"""Camera detector models.

Every detector converts an image of photon flux (photons/s per pixel) into gray
values with the same sequence of steps.  Detectors differ only in their parameters,
and in which steps do nothing for them:

1. **Expected signal.** Mean photoelectrons per pixel: flux x exposure, plus dark
   current x exposure, plus clock-induced charge (per frame).  QE is not applied
   here: it is applied (per wavelength) to the emission rates upstream, in
   `Simulation.filtered_emission_rates`.
2. **Shot noise.** Photon arrival and thermal generation are Poisson processes, so
   the number of electrons in each pixel is Poisson distributed.
3. **Full well.** A pixel cannot hold more than `full_well` electrons.  Charge
   binning (CCD) happens here, before readout.
4. **Multiplication.** Some detectors amplify each electron before readout (the EM
   register of an EMCCD, the dynodes of a PMT).  The gain `g` of each electron is
   random, which adds noise on top of shot noise.  This is summarized by the
   *excess noise factor*, `F = <g^2> / <g>^2 = 1 + var(g) / mean(g)^2`: the output
   variance is `F` times what a noiseless gain would give, so `SNR = sqrt(n / F)`.
   Gain noise acts like dividing the QE by `F`.  Detectors without multiplication
   have gain 1 and `F = 1`.
5. **Readout.** The amplifier adds Gaussian read noise (`read_noise`, electrons
   rms).  The ADC then converts electrons to gray values (the analog gain, set by
   `relative_gain` or `electrons_per_adu`), adds `offset`, rounds (which adds
   quantization noise), and clips to the range of `bit_depth`.  Digital binning
   (CMOS) happens after this step.

Read noise is modeled as a single term referred to the input, so it does not
change with analog gain or readout rate.
"""

import warnings
from typing import TYPE_CHECKING, Annotated, ClassVar, Literal

import numpy as np
import numpy.typing as npt
from annotated_types import Ge, Interval
from pydantic import Field, model_validator
from scipy import stats

from microsim._data_array import DataArray, xrDataArray
from microsim.schema._base_model import SimBaseModel
from microsim.schema.backend import NumpyAPI
from microsim.schema.spectrum import Spectrum
from microsim.util import bin_window

if TYPE_CHECKING:
    from typing import Self

    from microsim._data_array import ArrayProtocol

PositiveFloat = Annotated[float, Ge(0)]
PositiveInt = Annotated[int, Ge(0)]


def apply_multiplication_gain(
    electrons: npt.NDArray, gain: float, enf: float
) -> npt.NDArray:
    """Multiply each electron by a random gain with mean `gain` and noise factor `enf`.

    Each electron's gain is drawn from a gamma distribution with mean `gain` and
    variance `(enf - 1) * gain**2`.  A sum of `n` such gammas is itself gamma
    distributed, `Gamma(shape=n / (enf - 1), scale=gain * (enf - 1))`, so the whole
    pixel is drawn at once.  This matches the mean and variance of the true gain
    distribution, and is exact for an EMCCD at high gain, where each electron's gain
    is exponential (`enf` = 2).  At low gain and few input electrons the shape of the
    output distribution is only approximate (e.g. a real EM register rarely outputs
    fewer electrons than it receives, but at `gain` = 2 this outputs 0 for ~9% of
    single electrons), though its mean and variance remain correct.
    """
    electrons = np.asarray(electrons)
    if enf - 1 < 1e-9:  # noiseless gain
        return np.round(electrons * gain)
    shape = np.maximum(electrons, 1) / (enf - 1)  # gamma shape must be > 0
    out = stats.gamma.rvs(shape, scale=gain * (enf - 1), size=electrons.shape)
    return np.where(electrons > 0, np.round(out), 0)


class _Camera(SimBaseModel):
    """Base camera model (see module docstring for the simulation steps).

    Attributes
    ----------
    camera_type : str
        Type of camera, for discriminated union.
    read_noise : float
        Read noise, in electrons rms.
    qe : float | Spectrum
        Quantum efficiency, from 0-1: the probability that a photon creates a
        photoelectron.  A float is constant across wavelengths.
    full_well : int
        Maximum number of electrons a pixel can hold.
    serial_reg_full_well : int, optional
        Maximum number of electrons the serial (or EM) register can hold.
    dark_current : float
        Thermally generated electrons per pixel per second.
    clock_induced_charge : float
        Electrons per pixel per frame generated by clocking charge during readout.
    bit_depth : int
        ADC bit depth.  Gray values are clipped to `[0, 2**bit_depth - 1]`.
    offset : int
        Constant added to every pixel, in gray values, so that read noise is not
        clipped at zero.
    relative_gain : float, optional
        Analog (pre-amplifier) gain, relative to the setting at which `full_well`
        electrons map to the maximum gray value.  This is what microscope software
        usually calls a gain of 1.  Mutually exclusive with `electrons_per_adu`.
        Defaults to 1 if neither is given.  (Formerly `gain`.)
    electrons_per_adu : float, optional
        Analog gain as electrons per gray value, as listed on camera datasheets.
        Mutually exclusive with `relative_gain`.
    name : str
        A descriptive name for the camera.  Not used internally.
    """

    _renamed_fields: ClassVar[dict[str, str]] = {"gain": "relative_gain"}

    camera_type: str = "generic"
    read_noise: PositiveFloat = 6  # TODO: accept map of readout rate -> noise?
    qe: Annotated[float, Interval(ge=0, le=1)] | Spectrum = 1
    full_well: int = 18_000
    serial_reg_full_well: int | None = None
    dark_current: PositiveFloat = Field(0.001, description="e/pix/sec")
    clock_induced_charge: PositiveFloat = Field(0, description="e/pix/frame")
    bit_depth: PositiveInt = 12
    offset: int = 100
    relative_gain: Annotated[float, Field(gt=0)] | None = None
    electrons_per_adu: Annotated[float, Field(gt=0)] | None = None
    name: str = ""

    # TODO: add photodiode size ... this needs to be reconciled with the up/down-scaling
    # that we do elsewhere in the simulation
    # photodiode_size: float = 6.5

    @model_validator(mode="after")
    def _check_analog_gain(self) -> "Self":
        if self.relative_gain is not None and self.electrons_per_adu is not None:
            raise ValueError(
                "Specify either `relative_gain` or `electrons_per_adu`, not both."
            )
        return self

    @property
    def conversion_factor(self) -> float:
        """Electrons per gray value, from `electrons_per_adu` or `relative_gain`."""
        if self.electrons_per_adu is not None:
            return self.electrons_per_adu
        return self.full_well / (self.max_intensity * (self.relative_gain or 1))

    @property
    def multiplication_gain(self) -> float:
        """Mean gain applied to each electron before readout (1 if none)."""
        return 1

    @property
    def excess_noise_factor(self) -> float:
        """Excess noise factor of the multiplication step (1 if none)."""
        return 1

    def apply_pre_quantization_binning(
        self, total_electrons: npt.NDArray, binning: int
    ) -> npt.NDArray:
        # default implementation does nothing, implemented in CCD types
        return total_electrons

    def apply_post_quantization_binning(
        self, gray_values: npt.NDArray, binning: int
    ) -> npt.NDArray:
        # default implementation does nothing, implemented in CMOS types
        return gray_values

    def simulate(
        self,
        photons_per_second: "xrDataArray",
        exposure_ms: "float | xrDataArray" = 100,
        binning: int = 1,
        add_poisson: bool = True,
        xp: "NumpyAPI | None" = None,
    ) -> "ArrayProtocol":
        xp = NumpyAPI.create(xp)
        exposure_s = exposure_ms / 1000

        # 1-2. expected signal, and shot noise
        # NOTE: QE is applied upstream (Simulation.filtered_emission_rates), not here.
        # This is only correct if the optical image was computed with this detector;
        # see https://github.com/tlambert03/microsim/issues/152
        incident_photons = xp.maximum((photons_per_second * exposure_s).data, 0)
        if add_poisson:
            electrons = xp.poisson_rvs(incident_photons, shape=incident_photons.shape)
        else:
            electrons = incident_photons
        # dark current and clock-induced charge (mean electrons per pixel)
        avg_dark_e = self.dark_current * exposure_s + self.clock_induced_charge
        if not isinstance(avg_dark_e, float | int):  # per-channel exposure
            new_shape = avg_dark_e.shape + (1,) * (electrons.ndim - 1)
            avg_dark_e = np.asarray(avg_dark_e).reshape(new_shape)  # type: ignore[assignment]
        electrons = electrons + xp.poisson_rvs(avg_dark_e, shape=electrons.shape)

        # 3. full well, and charge binning
        electrons = xp.minimum(electrons, self.full_well)
        if binning > 1:
            electrons = self.apply_pre_quantization_binning(electrons, binning)

        # 4. multiplication, and serial register full well
        if self.multiplication_gain != 1:
            electrons = apply_multiplication_gain(
                electrons, self.multiplication_gain, self.excess_noise_factor
            )
        if self.serial_reg_full_well is not None:
            electrons = xp.minimum(electrons, self.serial_reg_full_well)

        # 5. readout: read noise, ADC conversion, offset, digital binning, clipping
        electrons = xp.norm_rvs(electrons, self.read_noise)  # type: ignore[assignment]
        gray = xp.maximum(xp.round(electrons / self.conversion_factor + self.offset), 0)
        if binning > 1:
            gray = self.apply_post_quantization_binning(gray, binning)
        gray = xp.minimum(gray, self.max_intensity)
        if self.bit_depth > 16:
            return gray.astype("uint32")  # type: ignore[no-any-return]
        if self.bit_depth > 8:
            return gray.astype("uint16")  # type: ignore[no-any-return]
        return gray.astype("uint8")  # type: ignore[no-any-return]

    @property
    def dynamic_range(self) -> float:
        return self.full_well / self.read_noise

    def render(
        self,
        image: xrDataArray,
        exposure_ms: float | xrDataArray = 100,
        binning: int = 1,
        add_poisson: bool = True,
        xp: NumpyAPI | None = None,
    ) -> xrDataArray:
        """Simulate imaging process.

        Parameters
        ----------
        image : DataArray
            array where each element represents photons / second
        exposure_ms : float, optional
            Exposure time in milliseconds, by default 100
        binning : int, optional
            Binning to apply to the last two (Y, X) dimensions, by default 1
        add_poisson : bool, optional
            Whether to add poisson noise, by default True
        xp: NumpyAPI | None
            Numpy API backend
        """
        new_data = self.simulate(
            photons_per_second=image,
            exposure_ms=exposure_ms,
            binning=binning,
            add_poisson=add_poisson,
            xp=xp,
        )
        if binning > 1:
            yx = dict.fromkeys(image.dims[-2:], binning)
            image = image.coarsen(yx, boundary="trim").mean()
        return DataArray(
            new_data, dims=image.dims, coords=image.coords, attrs=image.attrs
        )

    @property
    def max_intensity(self) -> int:
        return int(2**self.bit_depth - 1)

    @property
    def gain(self) -> float:
        """Deprecated: the analog gain as a relative gain (see `relative_gain`)."""
        warnings.warn(
            "`gain` has been renamed to `relative_gain`.", FutureWarning, stacklevel=2
        )
        return self.full_well / (self.max_intensity * self.conversion_factor)


def _bin_yx(array: npt.NDArray, binning: int, method: str) -> npt.NDArray:
    """Bin the last two (Y, X) dimensions of `array`."""
    window = (1,) * (array.ndim - 2) + (binning, binning)
    return bin_window(np.asarray(array), window, method=method)


class CameraCCD(_Camera):
    """Charge-coupled device (CCD).

    All pixels shift their charge to a single output amplifier, so read noise is
    added once per output pixel.  Binning combines charge before readout, which
    gives `binning**2` times the signal with the same read noise.
    """

    camera_type: Literal["CCD"] = "CCD"

    def apply_pre_quantization_binning(
        self, total_electrons: npt.NDArray, binning: int
    ) -> npt.NDArray:
        return _bin_yx(total_electrons, binning, "sum")


class CameraEMCCD(_Camera):
    """Electron-multiplying CCD (EMCCD).

    A CCD with an extra serial register of `em_stages` cells, clocked at high
    voltage.  At each cell, every electron has a small chance (~1-2%) of creating a
    second electron by impact ionization, for a mean total gain
    `em_gain = (1 + p) ** em_stages`.  This lifts the signal far above read noise,
    so single photons become visible.  The cost is gain noise: the number of
    electrons out of the register varies widely for the same number in, with an
    excess noise factor that approaches 2 at high gain.  An EMCCD therefore has the
    signal-to-noise ratio of an ideal detector with half its QE.

    `relative_gain`/`electrons_per_adu` set the separate analog gain of the readout
    amplifier.  `relative_gain` is relative to the pixel `full_well`, so at high EM
    gain `electrons_per_adu` is usually more convenient.

    Attributes
    ----------
    em_gain : float
        Mean gain of the EM register.
    em_stages : int
        Number of cells in the EM register (604 in e2v CCD201/CCD-311 sensors; see
        `excess_noise_factor`).
    """

    camera_type: Literal["EMCCD"] = "EMCCD"
    em_gain: Annotated[float, Field(ge=1)]
    em_stages: Annotated[int, Field(ge=1)] = 604

    @property
    def multiplication_gain(self) -> float:
        return self.em_gain

    @property
    def excess_noise_factor(self) -> float:
        """Excess noise factor of the EM register, which rises from 1 toward 2.

        `F = 2 (G - 1) G**(-(N + 1) / N) + 1 / G`, for mean gain `G` over `N` stages
        (Robbins & Hadwen 2003, IEEE Trans. Electron Devices 50:1227).  This follows
        from treating each stage as independent: an electron makes one extra
        electron with probability `p = G**(1/N) - 1`.  With 604 stages, `F` is 1 at
        `G = 1`, 1.5 at `G = 2`, 1.89 at `G = 10`, and about 1.98 for `G` of 100-1000.
        """
        g, n = self.em_gain, self.em_stages
        return float(2 * (g - 1) * g ** (-(n + 1) / n) + 1 / g)

    def apply_pre_quantization_binning(
        self, total_electrons: npt.NDArray, binning: int
    ) -> npt.NDArray:
        return _bin_yx(total_electrons, binning, "sum")


class CameraCMOS(_Camera):
    """CMOS (and sCMOS) camera.

    Each pixel has its own amplifier, and each column its own ADC, so read noise is
    added per pixel and binning is done digitally after readout (here, by averaging
    gray values).  Pixel-to-pixel variation in gain, offset, and noise is not
    modeled.
    """

    camera_type: Literal["CMOS"] = "CMOS"

    def apply_post_quantization_binning(
        self, gray_values: npt.NDArray, binning: int
    ) -> npt.NDArray:
        return _bin_yx(gray_values, binning, "mean")
