"""Camera detector models: CCD, EMCCD, and CMOS.

See `_detector.py` for the simulation steps shared by all detectors.
"""

import warnings
from typing import Annotated, Any, ClassVar, Literal

import numpy as np
import numpy.typing as npt
from pydantic import Field

from microsim.schema.backend import NumpyAPI
from microsim.util import bin_window

from ._detector import _Detector


class _Camera(_Detector):
    """Base camera model.

    A camera has an array of pixels, each storing charge during the exposure.

    Attributes
    ----------
    full_well : int
        Maximum number of electrons a pixel can hold.
    serial_reg_full_well : int, optional
        Maximum number of electrons the serial (or EM) register can hold.
    clock_induced_charge : float
        Electrons per pixel per frame generated by clocking charge during readout.
    """

    _renamed_fields: ClassVar[dict[str, str]] = {"gain": "relative_gain"}

    full_well: int = 18_000
    serial_reg_full_well: int | None = None
    clock_induced_charge: Annotated[float, Field(ge=0)] = Field(
        0, description="e/pix/frame"
    )

    # TODO: add photodiode size ... this needs to be reconciled with the up/down-scaling
    # that we do elsewhere in the simulation
    # photodiode_size: float = 6.5

    def _dark_electrons_per_frame(self) -> float:
        return self.clock_induced_charge

    def _after_multiplication(
        self, electrons: npt.NDArray, time_s: Any, xp: NumpyAPI
    ) -> npt.NDArray:
        if self.serial_reg_full_well is not None:
            return xp.minimum(electrons, self.serial_reg_full_well)  # type: ignore[no-any-return]
        return electrons

    @property
    def dynamic_range(self) -> float:
        return self.full_well / self.read_noise

    @property
    def gain(self) -> float:
        """Deprecated: the analog gain as a relative gain (see `relative_gain`)."""
        warnings.warn(
            "`gain` has been renamed to `relative_gain`.", FutureWarning, stacklevel=2
        )
        return self.full_well / (self.max_intensity * self.conversion_factor)

    @gain.setter
    def gain(self, value: float) -> None:
        warnings.warn(
            "`gain` has been renamed to `relative_gain`.", FutureWarning, stacklevel=2
        )
        self.electrons_per_adu = None
        self.relative_gain = value


def _bin_yx(array: npt.NDArray, binning: int, method: str) -> npt.NDArray:
    """Bin the last two (Y, X) dimensions of `array`."""
    *rest, ny, nx = array.shape
    window = (1,) * len(rest) + (binning, binning)
    binned = bin_window(np.asarray(array), window, method=method)
    return binned.reshape(*rest, ny // binning, nx // binning)  # undo squeeze


class CameraCCD(_Camera):
    """Charge-coupled device (CCD).

    All pixels shift their charge to a single output amplifier, so read noise is
    added once per output pixel.  Binning combines charge before readout, which
    gives `binning**2` times the signal with the same read noise.
    """

    camera_type: Literal["CCD"] = "CCD"

    def apply_pre_quantization_binning(
        self, total_electrons: npt.NDArray, binning: int
    ) -> npt.NDArray:
        return _bin_yx(total_electrons, binning, "sum")


class CameraEMCCD(_Camera):
    """Electron-multiplying CCD (EMCCD).

    A CCD with an extra serial register of `em_stages` cells, clocked at high
    voltage.  At each cell, every electron has a small chance (~1-2%) of creating a
    second electron by impact ionization, for a mean total gain
    `em_gain = (1 + p) ** em_stages`.  This lifts the signal far above read noise,
    so single photons become visible.  The cost is gain noise: the number of
    electrons out of the register varies widely for the same number in, with an
    excess noise factor that approaches 2 at high gain.  An EMCCD therefore has the
    signal-to-noise ratio of an ideal detector with half its QE.

    `relative_gain`/`electrons_per_adu` set the separate analog gain of the readout
    amplifier.  `relative_gain` is relative to the pixel `full_well`, so at high EM
    gain `electrons_per_adu` is usually more convenient.

    Attributes
    ----------
    em_gain : float
        Mean gain of the EM register.
    em_stages : int
        Number of cells in the EM register (604 in e2v CCD201/CCD-311 sensors; see
        `excess_noise_factor`).
    """

    camera_type: Literal["EMCCD"] = "EMCCD"
    em_gain: Annotated[float, Field(ge=1)]
    em_stages: Annotated[int, Field(ge=1)] = 604

    @property
    def multiplication_gain(self) -> float:
        return self.em_gain

    @property
    def excess_noise_factor(self) -> float:
        """Excess noise factor of the EM register, which rises from 1 toward 2.

        `F = 2 (G - 1) G**(-(N + 1) / N) + 1 / G`, for mean gain `G` over `N` stages
        (Robbins & Hadwen 2003, IEEE Trans. Electron Devices 50:1227).  This follows
        from treating each stage as independent: an electron makes one extra
        electron with probability `p = G**(1/N) - 1`.  With 604 stages, `F` is 1 at
        `G = 1`, 1.5 at `G = 2`, 1.89 at `G = 10`, and about 1.98 for `G` of 100-1000.
        """
        g, n = self.em_gain, self.em_stages
        return float(2 * (g - 1) * g ** (-(n + 1) / n) + 1 / g)

    def apply_pre_quantization_binning(
        self, total_electrons: npt.NDArray, binning: int
    ) -> npt.NDArray:
        return _bin_yx(total_electrons, binning, "sum")


class CameraCMOS(_Camera):
    """CMOS (and sCMOS) camera.

    Each pixel has its own amplifier, and each column its own ADC, so read noise is
    added per pixel and binning is done digitally after readout (here, by averaging
    gray values).  Pixel-to-pixel variation in gain, offset, and noise is not
    modeled.
    """

    camera_type: Literal["CMOS"] = "CMOS"

    def apply_post_quantization_binning(
        self, gray_values: npt.NDArray, binning: int
    ) -> npt.NDArray:
        return _bin_yx(gray_values, binning, "mean")
